server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

spring:
  cloud:
    gateway:
      routes:

        # User Service Routes
        - id: user-service-route
          uri: lb://user-service-impl          # lb = load balanced via Eureka
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1               # strips /api before forwarding

        # Product Service Routes
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
management:
  tracing:
    sampling:
      probability: 1.0    # ← trace 100% of requests
                          # in production use 0.1 (10%)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
