server:
  port: 8099

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # User Service Routes
        - id: user-service-route
          uri: lb://user-service-impl
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        # Product Service Routes
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    org.springframework.cloud.gateway: INFO

  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
