spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/shopzone_product?createDatabaseIfNotExist=true
    username: root
    password: ${SPRING_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

file:
  uploadDir: uploads

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema: DEBUG

  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
