spring:
  application:
    name: user-service-impl

  datasource:
    url: jdbc:mysql://localhost:3306/shopzone_users?createDatabaseIfNotExist=true
    username: root
    password: ${SPRING_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    # baseline-on-migrate: true   # enable only first migration if needed

  mail:
    host: smtp.gmail.com
    port: 587
    username: hacktivistcyber22@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org:
      flywaydb: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        tool:
          schema: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
