spring:
  application:
    name: user-service-impl

  datasource:
    url: jdbc:mysql://localhost:3306/shopzone_users?createDatabaseIfNotExist=true
    username: root
    password: ${SPRING_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    # baseline-on-migrate: true   # enable only first migration if needed

  mail:
    host: smtp.gmail.com
    port: 587
    username: hacktivistcyber22@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org:
      flywaydb: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        tool:
          schema: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:

  circuitbreaker:
    instances:
      productServiceCB:             # ← this name you will use in annotation
        sliding-window-size: 10     # watch last 10 requests
        failure-rate-threshold: 50  # if 50% fail → OPEN
        wait-duration-in-open-state: 30s   # stay OPEN for 30 secs
        permitted-number-of-calls-in-half-open-state: 3  # test with 3 calls
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      productServiceRetry:          # ← this name you will use in annotation
        max-attempts: 3             # try 3 times total
        wait-duration: 2s           # wait 2 seconds between retries

  timelimiter:
    instances:
      productServiceCB:
        timeout-duration: 4s        # if no response in 4s → failure

# See circuit breaker state via actuator
management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
