spring:
  application:
    name: user-service-impl

  datasource:
    url: jdbc:mysql://localhost:3306/shopzone_users?createDatabaseIfNotExist=true
    username: root
    password: ${SPRING_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hacktivistcyber22@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org:
      flywaydb: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        tool:
          schema: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Resilience4j  CONFIG
resilience4j:

  circuitbreaker:
    instances:
      productServiceCB:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

        # 
        record-exceptions:
          - feign.FeignException
          - java.io.IOException
          - java.lang.Exception

  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.lang.Exception

# 

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true
